description: >
  CircleCI's Ubuntu-based machine executor VM:
  https://circleci.com/docs/2.0/executor-types/#using-machine

parameters:
  image:
    type: string
    default: ubuntu-1604:201903-01
  aws-access-key-id:
    description: >
      AWS access key id for IAM role. Set this to the name of
      the environment variable you will set to hold this
      value, i.e. AWS_ACCESS_KEY.
    type: env_var_name
    default: AWS_ACCESS_KEY_ID
  aws-secret-access-key:
    description: >
      AWS secret key for IAM role. Set this to the name of
      the environment variable you will set to hold this
      value, i.e. AWS_SECRET_ACCESS_KEY
    type: env_var_name
    default: AWS_SECRET_ACCESS_KEY
  account-url:
    description: >
      Env var storing Amazon ECR account URL that maps to an AWS account,
      e.g. {awsAccountNum}.dkr.ecr.us-west-2.amazonaws.com
      defaults to AWS_ECR_ACCOUNT_URL
    type: env_var_name
    default: AWS_ECR_ACCOUNT_URL
  region:
    description: >
      Name of env var storing your AWS region information,
      defaults to AWS_REGION
    type: env_var_name
    default: AWS_REGION

machine:
  image: <<parameters.image>>

environment:
  AWS_ACCESS_KEY_ID: << parameters.aws-access-key-id >>
  AWS_SECRET_ACCESS_KEY: << parameters.aws-secret-access-key >>
  AWS_ECR_ACCOUNT_URL: << parameters.account-url >>
  AWS_REGION: << parameters.region >>
